import JSZip from 'jszip';
import {
  TemplateParams,
  generateAppGo,
  generateEncodingGo,
  generateExportGo,
  generateMainGo,
  generateRootCmd,
} from './templates/app';
import {
  generateModuleGo,
  generateKeeperGo,
  generateMsgServerGo,
  generateQueryServerGo,
  generateTypesKeysGo,
  generateTypesMsgsGo,
  generateTypesGenesisGo,
  generateTypesErrorsGo,
  generateTypesCodecGo,
} from './templates/modules';
import {
  generateTxProto,
  generateQueryProto,
  generateGenesisProto,
  generateBufYaml,
  generateBufGenYaml,
  generateDockerfile,
  generateDockerCompose,
  generateGithubCI,
  generateValidatorScript,
  generateDeployScript,
  generateGoMod,
  generateMakefile,
  generateReadme,
  generateGitignore,
  generateDevcontainerJson,
} from './templates/proto';

export interface BlockchainParams {
  name: string;
  symbol: string;
  description: string;
  consensus: string;
  supply: string;
  blockTime: string;
  inflationRate: string;
  features: string[];
  minStake: string;
  maxValidators: string;
  unbondingDays: string;
}

function toTemplateParams(params: BlockchainParams): TemplateParams {
  const chainId = params.name.toLowerCase().replace(/\s+/g, '-');
  const binaryName = chainId.replace(/-/g, '') + 'd';
  const modulePath = `github.com/${chainId}/${chainId}`;

  return {
    ...params,
    chainId,
    binaryName,
    modulePath,
  };
}

// Determine which custom modules to scaffold based on selected features
function getCustomModules(features: string[]): string[] {
  const modules: string[] = [];
  if (features.includes('smartContracts')) modules.push('wasm');
  if (features.includes('nft')) modules.push('nft');
  if (features.includes('governance')) modules.push('governance');
  return modules;
}

export async function generateCosmosSDKTemplate(params: BlockchainParams): Promise<Uint8Array> {
  const zip = new JSZip();
  const p = toTemplateParams(params);
  const root = zip.folder(p.chainId)!;

  // ══════════════════════════════════════════
  //  1. Root Files
  // ══════════════════════════════════════════
  root.file('README.md', generateReadme(p));
  root.file('Makefile', generateMakefile(p));
  root.file('go.mod', generateGoMod(p));
  root.file('.gitignore', generateGitignore(p));
  root.file('Dockerfile', generateDockerfile(p));
  root.file('docker-compose.yml', generateDockerCompose(p));

  // ══════════════════════════════════════════
  //  2. App Wiring (app/)
  // ══════════════════════════════════════════
  const appFolder = root.folder('app')!;
  appFolder.file('app.go', generateAppGo(p));
  appFolder.file('encoding.go', generateEncodingGo(p));
  appFolder.file('export.go', generateExportGo(p));

  // ══════════════════════════════════════════
  //  3. CLI Binary (cmd/)
  // ══════════════════════════════════════════
  const cmdBinaryFolder = root.folder('cmd')!.folder(p.binaryName)!;
  cmdBinaryFolder.file('main.go', generateMainGo(p));
  const cmdPkgFolder = cmdBinaryFolder.folder('cmd')!;
  cmdPkgFolder.file('root.go', generateRootCmd(p));

  // ══════════════════════════════════════════
  //  4. Config Files
  // ══════════════════════════════════════════
  const configFolder = root.folder('config')!;

  configFolder.file('config.toml', `# ${p.name} - CometBFT Configuration
# Generated by ChainForge AI

[consensus]
timeout_propose = "3s"
timeout_prevote = "1s"
timeout_precommit = "1s"
timeout_commit = "${p.blockTime}s"

[mempool]
max_txs_bytes = 1073741824
max_tx_bytes = 1048576
size = 5000

[p2p]
max_num_inbound_peers = 40
max_num_outbound_peers = 10
seed_mode = false
persistent_peers = ""

[statesync]
enable = false

[instrumentation]
prometheus = true
prometheus_listen_addr = ":26660"
max_open_connections = 3
`);

  configFolder.file('app.toml', `# ${p.name} - Application Configuration
# Generated by ChainForge AI

minimum-gas-prices = "0.025${p.symbol.toLowerCase()}"

[api]
enable = true
swagger = true
address = "tcp://0.0.0.0:1317"
max-open-connections = 1000

[grpc]
enable = true
address = "0.0.0.0:9090"

[grpc-web]
enable = true
address = "0.0.0.0:9091"

[state-sync]
snapshot-interval = 1000
snapshot-keep-recent = 2

[telemetry]
enabled = true
service-name = "${p.chainId}"
`);

  const genesisSupply = p.supply.replace(/[^0-9]/g, '') || '1000000000';
  configFolder.file('genesis.json', JSON.stringify({
    genesis_time: new Date().toISOString(),
    chain_id: p.chainId,
    initial_height: "1",
    consensus_params: {
      block: {
        max_bytes: "22020096",
        max_gas: "-1",
        time_iota_ms: "1000"
      },
      evidence: {
        max_age_num_blocks: "100000",
        max_age_duration: "172800000000000",
        max_bytes: "1048576"
      },
      validator: {
        pub_key_types: ["ed25519"]
      }
    },
    app_state: {
      auth: {
        params: {
          max_memo_characters: "256",
          tx_sig_limit: "7",
          tx_size_cost_per_byte: "10",
          sig_verify_cost_ed25519: "590",
          sig_verify_cost_secp256k1: "1000"
        },
        accounts: []
      },
      bank: {
        params: { send_enabled: [], default_send_enabled: true },
        balances: [],
        supply: [{ denom: p.symbol.toLowerCase(), amount: genesisSupply }],
        denom_metadata: [{
          description: `The native staking token of ${p.name}`,
          denom_units: [
            { denom: p.symbol.toLowerCase(), exponent: 0, aliases: [] },
            { denom: p.symbol.toUpperCase(), exponent: 6, aliases: [] }
          ],
          base: p.symbol.toLowerCase(),
          display: p.symbol.toUpperCase(),
          name: p.name,
          symbol: p.symbol.toUpperCase()
        }]
      },
      staking: {
        params: {
          unbonding_time: `${(parseInt(p.unbondingDays) || 21) * 86400}s`,
          max_validators: parseInt(p.maxValidators) || 100,
          max_entries: 7,
          historical_entries: 10000,
          bond_denom: p.symbol.toLowerCase(),
          min_commission_rate: "0.050000000000000000"
        }
      },
      mint: {
        minter: {
          inflation: `0.${(p.inflationRate || '7').padStart(2, '0')}0000000000000000`,
          annual_provisions: "0.000000000000000000"
        },
        params: {
          mint_denom: p.symbol.toLowerCase(),
          inflation_rate_change: "0.130000000000000000",
          inflation_max: "0.200000000000000000",
          inflation_min: "0.030000000000000000",
          goal_bonded: "0.670000000000000000",
          blocks_per_year: `${Math.floor(365.25 * 24 * 3600 / (parseInt(p.blockTime) || 2))}`
        }
      },
      distribution: {
        params: {
          community_tax: "0.020000000000000000",
          base_proposer_reward: "0.000000000000000000",
          bonus_proposer_reward: "0.000000000000000000",
          withdraw_addr_enabled: true
        }
      },
      slashing: {
        params: {
          signed_blocks_window: "100",
          min_signed_per_window: "0.500000000000000000",
          downtime_jail_duration: "600s",
          slash_fraction_double_sign: "0.050000000000000000",
          slash_fraction_downtime: "0.010000000000000000"
        }
      },
      gov: p.features.includes('governance') ? {
        params: {
          min_deposit: [{ denom: p.symbol.toLowerCase(), amount: "10000000" }],
          max_deposit_period: "172800s",
          voting_period: "172800s",
          quorum: "0.334000000000000000",
          threshold: "0.500000000000000000",
          veto_threshold: "0.334000000000000000",
          min_initial_deposit_ratio: "0.000000000000000000",
          burn_vote_quorum: false,
          burn_proposal_deposit_prevote: true,
          burn_vote_veto: true
        },
        proposals: [],
        deposits: [],
        votes: []
      } : undefined,
      crisis: {
        constant_fee: { denom: p.symbol.toLowerCase(), amount: "1000" }
      }
    }
  }, null, 2));

  // ══════════════════════════════════════════
  //  5. Custom Modules (x/)
  // ══════════════════════════════════════════
  const customModules = getCustomModules(p.features);

  for (const moduleName of customModules) {
    const modRoot = root.folder('x')!.folder(moduleName)!;

    // Module registration
    modRoot.file('module.go', generateModuleGo(p, moduleName));

    // Keeper
    const keeperDir = modRoot.folder('keeper')!;
    keeperDir.file('keeper.go', generateKeeperGo(p, moduleName));
    keeperDir.file('msg_server.go', generateMsgServerGo(p, moduleName));
    keeperDir.file('query_server.go', generateQueryServerGo(p, moduleName));

    // Types
    const typesDir = modRoot.folder('types')!;
    typesDir.file('keys.go', generateTypesKeysGo(p, moduleName));
    typesDir.file('msgs.go', generateTypesMsgsGo(p, moduleName));
    typesDir.file('genesis.go', generateTypesGenesisGo(p, moduleName));
    typesDir.file('errors.go', generateTypesErrorsGo(p, moduleName));
    typesDir.file('codec.go', generateTypesCodecGo(p, moduleName));
  }

  // ══════════════════════════════════════════
  //  6. Protobuf Definitions (proto/)
  // ══════════════════════════════════════════
  root.file('buf.yaml', generateBufYaml(p));
  root.file('buf.gen.yaml', generateBufGenYaml(p));

  for (const moduleName of customModules) {
    const protoModDir = root.folder('proto')!
      .folder(p.chainId.replace(/-/g, ''))!
      .folder(moduleName)!
      .folder('v1')!;

    protoModDir.file('tx.proto', generateTxProto(p, moduleName));
    protoModDir.file('query.proto', generateQueryProto(p, moduleName));
    protoModDir.file('genesis.proto', generateGenesisProto(p, moduleName));
  }

  // ══════════════════════════════════════════
  //  7. Scripts
  // ══════════════════════════════════════════
  const scriptsFolder = root.folder('scripts')!;
  scriptsFolder.file('init-validator.sh', generateValidatorScript(p));
  scriptsFolder.file('deploy.sh', generateDeployScript(p));

  // ══════════════════════════════════════════
  //  8. CI/CD & Cloud Deployment
  // ══════════════════════════════════════════
  const ciFolder = root.folder('.github')!.folder('workflows')!;
  ciFolder.file('ci.yml', generateGithubCI(p));

  const devcontainerFolder = root.folder('.devcontainer')!;
  devcontainerFolder.file('devcontainer.json', generateDevcontainerJson(p));

  // ══════════════════════════════════════════
  //  9. Tests (placeholder)
  // ══════════════════════════════════════════
  for (const moduleName of customModules) {
    const testDir = root.folder('x')!.folder(moduleName)!.folder('keeper')!;
    const capMod = moduleName.charAt(0).toUpperCase() + moduleName.slice(1);
    testDir.file('keeper_test.go', `package keeper_test

import (
\t"testing"

\t"github.com/stretchr/testify/require"
\tkeeper "${p.modulePath}/x/${moduleName}/keeper"
\t"${p.modulePath}/x/${moduleName}/types"
)

func TestNewKeeper(t *testing.T) {
\t// TODO: Set up test environment with mock store and codec
\tt.Skip("Requires test infrastructure setup")
}

func TestKeeper_GetParams(t *testing.T) {
\t// TODO: Initialize keeper, set params, and verify retrieval
\tt.Skip("Requires test infrastructure setup")
}

func TestKeeper_SetParams(t *testing.T) {
\t// TODO: Initialize keeper and verify param updates
\tt.Skip("Requires test infrastructure setup")
}

func TestMsgServer_UpdateParams(t *testing.T) {
\t// TODO: Test authority check and param update flow
\tt.Skip("Requires test infrastructure setup")
}
`);
  }

  const content = await zip.generateAsync({ type: 'uint8array' });
  return content;
}
