import { NextResponse } from 'next/server';
import { generateCosmosSDKTemplate, BlockchainParams } from '@/lib/generator';
import JSZip from 'jszip';
import { Octokit } from 'octokit';

export async function POST(req: Request) {
  try {
    const { token, formData } = await req.json();
    if (!token) return NextResponse.json({ error: "Missing GitHub token" }, { status: 400 });

    const octokit = new Octokit({ auth: token });
    
    // Test auth and get username
    const { data: user } = await octokit.rest.users.getAuthenticated();
    
    // 1. Generate ZIP
    const zipBuffer = await generateCosmosSDKTemplate(formData as BlockchainParams);
    const zip = await JSZip.loadAsync(zipBuffer);
    
    const repoName = (formData.name || "cosmos-chain").toLowerCase().replace(/\s+/g, '-');
    
    // 2. Create Repository
    let created = false;
    try {
      await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: formData.description || "Generated by ChainForge AI",
        private: false,
        auto_init: true // creates main branch with README
      });
      created = true;
    } catch (e: any) {
      if (e.status !== 422) throw e;
      // 422 means repository already exists, which is fine, we will push over it.
    }

    if (created) {
      // Wait a sec for auto_init to finish
      await new Promise(r => setTimeout(r, 1500));
    }

    // 3. Get current commit of main
    const { data: ref } = await octokit.rest.git.getRef({
      owner: user.login,
      repo: repoName,
      ref: 'heads/main'
    });
    const commitSha = ref.object.sha;

    const { data: commit } = await octokit.rest.git.getCommit({
      owner: user.login,
      repo: repoName,
      commit_sha: commitSha
    });
    const baseTreeSha = commit.tree.sha;

    // 4. Create new tree
    const files: any[] = [];
    zip.forEach((relativePath, zipEntry) => {
      if (!zipEntry.dir) {
        files.push({ relativePath, zipEntry });
      }
    });

    const tree = await Promise.all(files.map(async ({ relativePath, zipEntry }) => {
      const pathParts = relativePath.split('/');
      pathParts.shift(); // remove root folder (e.g., axiogen-chain)
      const finalPath = pathParts.join('/');
      
      const content = await zipEntry.async('string');
      return {
        path: finalPath,
        mode: '100644',
        type: 'blob',
        content: content,
      };
    }));

    const { data: newTree } = await octokit.rest.git.createTree({
      owner: user.login,
      repo: repoName,
      base_tree: baseTreeSha,
      tree: tree as any, // Type cast because of custom content field
    });

    // 5. Create new commit
    const { data: newCommit } = await octokit.rest.git.createCommit({
      owner: user.login,
      repo: repoName,
      message: 'Initial commit from ChainForge AI',
      tree: newTree.sha,
      parents: [commitSha]
    });

    // 6. Update ref
    await octokit.rest.git.updateRef({
      owner: user.login,
      repo: repoName,
      ref: 'heads/main',
      sha: newCommit.sha,
    });

    return NextResponse.json({
      success: true,
      url: `https://github.com/${user.login}/${repoName}`
    });
  } catch (error: any) {
    console.error('GitHub error:', error);
    return NextResponse.json(
      { error: 'Failed to push to GitHub', details: error.message },
      { status: 500 }
    );
  }
}
